### ISSUE TITLE
subscribed view (useView) does not re-run after doc delete while reducing

### ISSUE THREAD

**Issue by tronto** [Terreii/use-pouchdb#55]
[note]: # ' ^^ Provide a general summary of the issue in the title above. ^^ '

## Description
Adding and updating docs re-runs a saved view as expected and runs map and reduce (_sum) properly. Deleting docs does not re-run the view as expected and results in incorrect _sum calculation (no update).

[note]: # " Describe the problem you're encountering. "
[tip]: # ' Do NOT give us access or passwords to your actual CouchDB or PouchDB! '

## Steps to Reproduce

[note]: # ' Include commands to reproduce, if possible. curl is preferred. '
Delete doc from a saved view while reducing.

## Expected Behavior

[note]: # ' Tell us what you expected to happen. '
subscribed view should re-run after deleting document related to a subscribed view.

## Your Environment

[tip]: # ' Include as many relevant details about your environment as possible. '
[tip]: # ' You can paste the output of curl http://YOUR-COUCHDB:5984/ here. '

- CouchDB version used:
- 3.1.1
- PouchDB version used:
- 7.2.2
- React version used:
- 17.0.1
- Browser name and version:
- Firefox / ios / safari
- Operating system and version:
- Macos

## Additional Context

[tip]: # ' Add any other context about the problem here. '

**Comment by Terreii** [comment]
Thanks for reporting this bug!
It was a known one. I should have documented it. It also doesn't update when you update a document in a way, that would remove it from the view.
Up until now `useView`, when reducing, would only listen to the changes feed filtered by the view.
I did chosen this way, because I didn't know how to make it else fast.

In the next release it will update for every update. But it will only start an update if no update is already running. If that is the case, then it will start another one once the running one did finish.

This is the compromise I have come up. I can't just listen to view updates (for reduce), because
- Reduce doesn't have the doc IDs. So I can't check for updates that left the view.
- A user could reduce over a large set of docs, so it would probably very memory consuming if I would query with and without reduce, to get the doc IDs.

Not reduced views subscribe to the view-update and the IDs in the result.
